name: Build JDK 13

on:
  push:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - 'jdk13/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        USER_NAME: ${{ secrets.USER_NAME }}  
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo $PASSWORD | docker login --username $USER_NAME --password-stdin

    - name: Build & Push Docker Image
      run: |
        cd jdk13
        IMAGE_NAME=ringcentral/jdk
        VERSION="$(awk -F= '/JAVA_VERSION=/ {print $2}' Dockerfile | cut -d " " -f 1)"
        BASE_VERSION="alpine$(awk -F '[:]' '/FROM/ {print $2}' Dockerfile)"
        docker build --tag ${IMAGE_NAME} --file Dockerfile .
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}"
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}-${BASE_VERSION}"
        docker push "${IMAGE_NAME}:${VERSION}-${BASE_VERSION}"
        docker push "${IMAGE_NAME}:${VERSION}"
